stages:
  - build
  - package
  - deploy

variables:
  HARBOR_HOST: core.harbor.brycehan.com
  APP_HOST: admin.cloud.brycehan.com
  NAMESPACE: bryce-cloud
  WORKLOAD: bryce-admin
  IMAGE_NAME: $HARBOR_HOST/bryce/bryce-admin:latest

build:
  stage: build
  image: node:18-alpine
  when: always
  only:
    - main
  script:
    - npm config set registry=https://registry.npmmirror.com
    - npm i
    - npm run build-only
  artifacts:
    name: "${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}"
    expire_in: 1hrs
    paths:
      - dist
  tags:
    - bryce-runner

package:
  stage: package
  image: $HARBOR_HOST/bryce-docker/buildah:latest
  when: on_success
  only:
    - main
  script:
    - /buildah.sh -t=$IMAGE_NAME
  tags:
    - bryce-runner

deploy:
  stage: deploy
  image: $HARBOR_HOST/bryce-docker/kubectl:latest
  when: on_success
  only:
    - main
  script:
    - /deploy.sh -n=$NAMESPACE -w=$WORKLOAD -i=$IMAGE_NAME -h=$APP_HOST
  tags:
    - bryce-runner
